    apiVersion: v1
    kind: Service
    metadata:
      name: webapp-service
      annotations:
        nginx.org/lb-method: "round_robin"
    spec:
      selector:
        app: webapp
      ports:
        - protocol: TCP
          port: 80
          targetPort: 5678
      type: LoadBalancer
